config/routes.rb
LousyLandLord::Application.routes.draw do
  get "users/new"

  get "comments/new"

  get "landlords/new"

  resources :landlords do 
    resources :comments
  end
  resources :sessions
  resources :addresses
  resources :comments
  
  resources :users
  resources :searches


  root :to =>  'static_pages#home'

  get '/submit', to: 'landlords#new'
  get '/search', to: 'searches#new'
  get '/home', to: 'static_pages#home'
  get '/tos', to: 'static_pages#TermsOfService'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  patch '/create_comment', to: 'landlords#create_comment'
  post '/address_searching', to: 'searches#create_address_search'
  post '/landlord_searching', to: 'searches#create_landlord_search'
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save {self.email = email.downcase}
  before_create :create_remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
		uniqueness: { case_sensitivity: false }

  has_secure_password
  validates :password, length: { minimum: 6 }	

  def User.new_remember_token
	  SecureRandom.urlsafe_base64
	end

  def User.encrypt(token)
	  Digest::SHA1.hexdigest(token.to_s)
  end

  private

	def create_remember_token
	  self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, 
                only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)  
  	if @user.save
      sign_in @user
      flash[:success] = "Welcome to Lousy Landlord!"
  	  redirect_to root_url
    else
      flash[:error] = "An error occured while signing up"
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<%= f.label "Landlord's Name : " %>
	<%= f.text_field :name %>
	<%= f.label "Comment : ", class: "tos"  %>
	<%= f.text_area :comment, :cols =>  "30", :rows => "10" %>
	<%= f.label "Terms of Service", class: "tos underline center" %>
	<div class="terms">
		<p class= "terms-closed" >"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum." </p>
	</div>
	<%= f.label "Agree to our terms of sevice" %>
	<%= f.check_box :terms %>



	<%= f.submit "Submit", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Landlord Results</h1>
<div class="center" > 
	<input type="text" class="search-query" placeholder="Filter name ... ">
</div>
<br>
<table class='table table-hover'>
<th>Landlord's Name</th>
<th>User Comment</th>

  <% @users.each do |u| %>

    <tr >     
      <td class='user-list'>
      	<%= content_tag(:p, u.name,  :data => {:name => u.name }) %> 
      </td>
      <td>
      	<%= u.try(:comment) %>
      </td>      
    </tr>
  <% end %>
</table>
<%= link_to 'Submit a Landlord', submit_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Landlord's name :</b>
  <%= @user.name %>
</p>


<p>
  <b>Ip:</b>
  <%= @user.ip %>
</p>

<p>
  <b>Comment:</b>
  <%= @user.comment %>
</p>

<p>
  <b>Submit:</b>
  <%= @user.submit %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>