config/routes.rb
LousyLandLord::Application.routes.draw do
  get "users/new"

  get "comments/new"

  get "landlords/new"

  resources :landlords do 
    resources :comments
  end
  resources :sessions
  resources :addresses
  resources :comments
  
  resources :users
  resources :searches


  root :to =>  'static_pages#home'

  get '/submit', to: 'landlords#new'
  get '/search', to: 'searches#new'
  get '/home', to: 'static_pages#home'
  get '/tos', to: 'static_pages#TermsOfService'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  patch '/create_comment', to: 'landlords#create_comment'
  post '/address_searching', to: 'searches#create_address_search'
  post '/landlord_searching', to: 'searches#create_landlord_search'
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
end

app/views/shared/_error_messages.html.erb
<% if @landlord.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-error">
		The form contains <%= pluralize(@landlord.errors.count, "error") %>.
	</div>
	<ul>
		<% @landlord.errors.full_messages.each do |msg| %>
		<li>* <%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_landlord_comments.html.erb
<% @landlord.comments.each do |f| %>
	<% if f.valid? %> 
		<%= content_tag :p, f.comment , class:'comment-text ' %> 
		<% if signed_in? && admin? %>		
			<%= link_to 'Delete', landlord_comment_path(@landlord, f), method: :delete %><br>
	    <% end %>
	<% end %>
<% end %>
        	