config/routes.rb
LousyLandLord::Application.routes.draw do
  get "users/new"

  get "comments/new"

  get "landlords/new"

  resources :landlords do 
    resources :comments
  end
  resources :sessions
  resources :addresses
  resources :comments
  
  resources :users
  resources :searches


  root :to =>  'static_pages#home'

  get '/submit', to: 'landlords#new'
  get '/search', to: 'searches#new'
  get '/home', to: 'static_pages#home'
  get '/tos', to: 'static_pages#TermsOfService'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  patch '/create_comment', to: 'landlords#create_comment'
  post '/address_searching', to: 'searches#create_address_search'
  post '/landlord_searching', to: 'searches#create_landlord_search'
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
end

app/models/landlord.rb
class Landlord < ActiveRecord::Base

    has_many :comments, dependent: :destroy
    has_many :addresses, dependent: :destroy

    belongs_to :province
    belongs_to :city

    accepts_nested_attributes_for :comments, :addresses, allow_destroy: true

    validates :name, presence: true, 
    				length: {minimum: 2, maximum: 50}

    validates :city_id, presence: true
    validates :province_id, presence: true
    
   	
	def self.search(search)
		if search
			find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end

    self.per_page = 10
    
    default_scope {order('landlords.name ASC')}
 

end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  def new
  	@landlord = Landlord.new
  end

  def index
    @landlords = Landlord.paginate(page: params[:landlord]).order(:name).search(params[:search])
  end

  def show  	
    @landlord = Landlord.find(params[:id])
    gon.addresses = Address.where(landlord_id: params[:id])
    gon.city_id = Landlord.find(params[:id]).city_id
    gon.landlords = Landlord.where(city_id: gon.city_id)
    gon.city = City.find(gon.city_id).name + ", " + Province.find(City.find(gon.city_id).province_id).name 
  end

  def create  	

    other_params = params[:landlord].slice!(:name, :city_id, :province_id, :user, :user_id)
    # check if the landlord checkbox is checked
    if params[:landlord][:user] == '1'
      @landlord = Landlord.find_or_initialize_by(params[:landlord].permit(:name, :city_id, :province_id, :user_id))
    elsif
      @landlord = Landlord.find_or_initialize_by(params[:landlord].permit(:name, :city_id, :province_id))
    end
    if @landlord.save 
      flash[:success] = "Thank you for submitting a landlord"
      redirect_to @landlord
    else
      render :new
    end

   end


   def update
    
    @landlord = Landlord.find(params[:id])

  end

  def destroy
    Landlord.find(params[:id]).destroy
    flash[:success] = "Landlord destroyed."
    redirect_to landlords_url
  end


private
  def landlord_params
    params.require(:landlord).permit(:name, :city_id, :province_id)
  end
  
  def find_by_params( sname,scity_id,sprovince_id)
    find_params = {name: sname, city_id: scity_id, province_id: sprovince_id}
    Landlord.find_by find_params    
  end 


end
 

app/helpers/landlords_helper.rb
module LandlordsHelper

	def google_maps_api_key
    	"AIzaSyCCVGCUC_hB_uWpUCOxto86juGXy9U0ve4"
  	end

  	def google_api_url
    	"https://maps.googleapis.com/maps/api/js"
  	end

  	def google_api_access
    	"#{google_api_url}?key=#{google_maps_api_key}&libraries=geometry&sensor=false"
  	end

  	def google_maps_api
    	content_tag(:script, :type => "text/javascript", :src => google_api_access) do
    	end
  	end
end

app/views/landlords/_address_form.html.erb
<div class="show-left">
  
      <p> Don't see the address? <a href="#" id="address-form-toggle">Add click here to add one</a> </p>

  <div class="half address-form ">
    <%= bootstrap_form_for(:address, url: addresses_path) do  |address_form| %>

    <!-- not safe?!? -->
    <% if @landlord.id %>
      <%= hidden_field_tag 'id', @landlord.id  %> 
      <%= hidden_field_tag 'city_id', @landlord.city.id  %>
      <%= hidden_field_tag 'province_id', @landlord.province.id  %>  
    <% end %>
    

    <%= address_form.text_field :number ,placeholder: "example: 123"%>
    <%= address_form.text_field :street ,placeholder: "example: Fake Street"%>
    <%= address_form.text_field :unit, placeholder: "example: 321"  %>
    <%= address_form.text_field :postal ,placeholder: "example: A1B 2C3" %><br/>
    <%= address_form.submit "Save Address",  class:"btn btn-primary" %>

    <% end %>
  </div>

</div>

app/views/landlords/_address_list.html.erb
<% if @landlord.addresses.any? %>
			<%  @landlord.addresses.each do |f| %>
				<p>
					<%= link_to_function "#{f.number} #{f.street}, Apt/Unit: #{f.unit}, postal code: #{f.postal}", "centerMapOnCoordinates(#{f.latitude}, #{f.longitude})" %>
					<br>
					<% if signed_in? && (admin? || @landlord.user_id == current_user.id) %>
						<%= link_to 'Delete', f, method: :delete,
                                     			 data: { confirm: "You sure?" },
                                     			 title: f %><br>
					<% end %>
				</p>
			<% end %>
		<% end %>

app/views/landlords/_comment_section.html.erb
<div class = "comment-section" >
	<h3>Leave a comment</h3>
	<span>Total comments : <%= @landlord.comments.count %> </span> 

	<%= form_for(:comment, url: comments_path) do |comment_form| %>
	<%= comment_form.text_area :comment, :rows => "10", 
	class:'frm-exp' , placeholder: 	"Comments must be between 15 and 500 characters!" %>
    <%= hidden_field_tag 'id', @landlord.id  %> 
	<div>
		<%= comment_form.submit "Submit", class:"btn btn-primary" %>
	</div>	
	<% end %>	
	<% if @landlord.comments.any? %>
		<%= render partial: 'shared/landlord_comments' %>
	<% else %>
		<%= content_tag :strong, "No comments" , class:'comment-text ' %> 			
	<% end %>
</div>

app/views/landlords/index.html.erb
<h1>Landlord Results</h1>
<div class="center" > 
	<input type="text" class="search-query" placeholder="Filter name ... ">
  <!--<br/><br/>

  <%= link_to "View map", root_url %> Will link to full page map if search was made by city -->
</div>
<br>
<table class='table table-hover'>
<th>Landlord's Name</th>
<th>User Comment Total</th>
<th>See profile</th>
<% if signed_in? && admin? %>
  <th>Delete</th>
<% end %>
  <% @landlords.each do |l| %>
    <tr >     
      <td class='user-list'>
      	<%= content_tag(:p, l.name,  :data => {:name => l.name }) %> 
      </td>
      <td>
      	<%= l.comments.count %>
      </td>      
      <td>
      	<%= link_to 'Profile', l %>
      </td>
      <% if signed_in? && admin? %>
        <td><%= link_to 'Delete', l, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: l.name %>
        </td>
      <% end %>
    </tr>
  <% end %>

</table>

<%= will_paginate %>

<%= link_to 'Submit a Landlord', submit_path %> 

app/views/landlords/new.html.erb
<div class="light-font ctr half">

	<h1 class="center">Submit a Landlord!</h1>


	<%= render '/shared/error_messages' %>

	<%= bootstrap_form_for @landlord do |f| %>

	<div >
			<%= f.text_field :name  %>
			<%= f.collection_select :province_id, Province.order(:name), :id, :name, include_blank: true %>		
			<%= f.grouped_collection_select :city_id, Province.order(:name), :cities, :name,  :id, :name, include_blank: true %>	
	</div>


	<div class="center submit">
		<%= f.submit "Submit", class: " btn btn-large btn-primary" %>
	</div>
	<% end %>


</div>

app/views/landlords/show.html.erb
<%= render '/shared/error_messages' %>
<%= include_gon %>
<div class="show-contents">
	
	<div >	
		<h1 class="light-font"> <%= @landlord.name %> </h1>
		<div id="map_canvas" ></div>
		<div class="light-font"	>
			<div class="show-left">
				<h3> <%= @landlord.city.name %>, <%= @landlord.province.name %> </h3>
				<%= render 'address_list' %>
			</div>
			<div >
				<%= render 'comment_section' %>
			</div>
			
	        <%= render 'address_form' %>
	        </div>
	</div>
</div>	