config/routes.rb
LousyLandLord::Application.routes.draw do
  get "users/new"

  get "comments/new"

  get "landlords/new"

  resources :landlords do 
    resources :comments
  end
  resources :sessions
  resources :addresses
  resources :comments
  
  resources :users
  resources :searches


  root :to =>  'static_pages#home'

  get '/submit', to: 'landlords#new'
  get '/search', to: 'searches#new'
  get '/home', to: 'static_pages#home'
  get '/tos', to: 'static_pages#TermsOfService'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  patch '/create_comment', to: 'landlords#create_comment'
  post '/address_searching', to: 'searches#create_address_search'
  post '/landlord_searching', to: 'searches#create_landlord_search'
  get '/signin', to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href=""> Lousy Landlord </a>
    by <%= link_to "Devon Ring", "http://devonring.ca" %> and <%= link_to "Frederic Marchand", "http://fredericmarchand.net" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '/about' %></li>
      <li><%= link_to "Contact", '/contact' %></li>
      <li><%= link_to "Terms of Service", '/tos' %></li>      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "LousyLandLord - DEMO PAGE", '/home', id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Home",    '/home' %></li>
          <li><%= link_to "Submit",    '/submit' %></li>
          <li><%= link_to "Search", new_search_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Sign out", signout_path %></li>
          <% end %> 
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  
  <%= google_maps_api %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>  
      <% end %>
      <%= yield %>
      
    </div>
    <!-- <%= render 'layouts/footer' %> -->
    <br/>
    <!--- <%= debug(params) if Rails.env.development? %>   -->
  </body>
</html>